"""schedule tables and active view

Revision ID: 2818ae3709f8
Revises: e1ebd45ab922
Create Date: 2026-08-24 01:33:08.620616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2818ae3709f8'
down_revision: Union[str, Sequence[str], None] = 'e1ebd45ab922'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('schedule_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('schedule_type', sa.String(length=20), nullable=False),
    sa.Column('solver_status', sa.String(length=20), nullable=False),
    sa.Column('objective_value', sa.Float(), nullable=False),
    sa.Column('makespan', sa.Integer(), nullable=False),
    sa.Column('total_tardiness', sa.Integer(), nullable=False),
    sa.Column('alpha_weight', sa.Float(), nullable=False),
    sa.Column('beta_weight', sa.Float(), nullable=False),
    sa.Column('time_limit_seconds', sa.Integer(), nullable=False),
    sa.Column('solve_duration_seconds', sa.Float(), nullable=False),
    sa.Column('failed_machine_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('parent_version_id', sa.Integer(), nullable=True),
    sa.Column('rolled_back', sa.Boolean(), nullable=False),
    sa.Column('committed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('payload_hash', sa.String(length=64), nullable=False),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint("schedule_type IN ('BASELINE','RECOVERY')", name=op.f('ck_schedule_versions_schedule_version_type')),
    sa.CheckConstraint("solver_status IN ('OPTIMAL','FEASIBLE','INFEASIBLE')", name=op.f('ck_schedule_versions_schedule_version_status')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_schedule_versions_instance_id_instances')),
    sa.ForeignKeyConstraint(['parent_version_id'], ['schedule_versions.id'], name=op.f('fk_schedule_versions_parent_version_id_schedule_versions')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_versions')),
    sa.UniqueConstraint('instance_id', 'version_number', name='uq_schedule_versions_instance_version')
    )
    op.create_index(op.f('ix_schedule_versions_instance_id'), 'schedule_versions', ['instance_id'], unique=False)
    op.create_table('schedule_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('version_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Integer(), nullable=False),
    sa.Column('end_time', sa.Integer(), nullable=False),
    sa.Column('processing_time', sa.Integer(), nullable=False),
    sa.Column('setup_time', sa.Integer(), nullable=False),
    sa.Column('is_frozen', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('SCHEDULED','FROZEN')", name=op.f('ck_schedule_entries_entry_status')),
    sa.CheckConstraint('end_time >= start_time', name=op.f('ck_schedule_entries_entry_interval_valid')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_schedule_entries_instance_id_instances')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_schedule_entries_machine_id_machines')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_schedule_entries_operation_id_operations')),
    sa.ForeignKeyConstraint(['version_id'], ['schedule_versions.id'], name=op.f('fk_schedule_entries_version_id_schedule_versions')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_schedule_entries_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_schedule_entries'))
    )
    op.create_index(op.f('ix_schedule_entries_instance_id'), 'schedule_entries', ['instance_id'], unique=False)
    op.create_index(op.f('ix_schedule_entries_version_id'), 'schedule_entries', ['version_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(
        """
        CREATE VIEW active_schedule AS
        SELECT se.* FROM schedule_entries se
        JOIN schedule_versions sv ON se.version_id = sv.id
        WHERE sv.id = (
            SELECT id FROM schedule_versions
            WHERE instance_id = se.instance_id
              AND solver_status IN ('OPTIMAL', 'FEASIBLE')
              AND rolled_back = false
            ORDER BY version_number DESC LIMIT 1
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("DROP VIEW IF EXISTS active_schedule")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_schedule_entries_version_id'), table_name='schedule_entries')
    op.drop_index(op.f('ix_schedule_entries_instance_id'), table_name='schedule_entries')
    op.drop_table('schedule_entries')
    op.drop_index(op.f('ix_schedule_versions_instance_id'), table_name='schedule_versions')
    op.drop_table('schedule_versions')
    # ### end Alembic commands ###
