"""fjsp core tables

Revision ID: 38432f3997b1
Revises: 4b782d560dd7
Create Date: 2026-08-23 02:58:01.784827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38432f3997b1'
down_revision: Union[str, Sequence[str], None] = '4b782d560dd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_families',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_job_families_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_job_families')),
    sa.UniqueConstraint('id', 'instance_id', name='uq_job_families_id_instance')
    )
    op.create_index(op.f('ix_job_families_instance_id'), 'job_families', ['instance_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('job_family_id', sa.Integer(), nullable=True),
    sa.Column('release_time', sa.Integer(), nullable=False),
    sa.Column('deadline', sa.Integer(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','IN_PROGRESS','COMPLETED','BLOCKED')", name=op.f('ck_jobs_job_status')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_jobs_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_jobs')),
    sa.UniqueConstraint('id', 'instance_id', name='uq_jobs_id_instance')
    )
    op.create_index(op.f('ix_jobs_instance_id'), 'jobs', ['instance_id'], unique=False)
    op.create_table('machines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('ACTIVE','FAILED','MAINTENANCE')", name=op.f('ck_machines_machine_status')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_machines_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machines')),
    sa.UniqueConstraint('id', 'instance_id', name='uq_machines_id_instance')
    )
    op.create_index(op.f('ix_machines_instance_id'), 'machines', ['instance_id'], unique=False)
    op.create_table('machine_capabilities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('capability_code', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=160), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_machine_capabilities_instance_id_instances')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_capabilities_machine_id_machines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_capabilities'))
    )
    op.create_index(op.f('ix_machine_capabilities_instance_id'), 'machine_capabilities', ['instance_id'], unique=False)
    op.create_table('operations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=True),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('required_role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('PENDING','SCHEDULED','IN_PROGRESS','COMPLETED','INTERRUPTED','BLOCKED')", name=op.f('ck_operations_operation_status')),
    sa.CheckConstraint('sequence_number >= 1', name=op.f('ck_operations_sequence_min')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_operations_instance_id_instances')),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], name=op.f('fk_operations_job_id_jobs')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_operations')),
    sa.UniqueConstraint('id', 'instance_id', name='uq_operations_id_instance'),
    sa.UniqueConstraint('job_id', 'sequence_number', name='uq_operations_job_sequence')
    )
    op.create_index(op.f('ix_operations_instance_id'), 'operations', ['instance_id'], unique=False)
    op.create_table('setup_times',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('from_family_id', sa.Integer(), nullable=True),
    sa.Column('to_family_id', sa.Integer(), nullable=True),
    sa.Column('setup_duration', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['from_family_id'], ['job_families.id'], name=op.f('fk_setup_times_from_family_id_job_families')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_setup_times_instance_id_instances')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_setup_times_machine_id_machines')),
    sa.ForeignKeyConstraint(['to_family_id'], ['job_families.id'], name=op.f('fk_setup_times_to_family_id_job_families')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_setup_times'))
    )
    op.create_index(op.f('ix_setup_times_instance_id'), 'setup_times', ['instance_id'], unique=False)
    op.create_table('operation_machine_alternatives',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('processing_time', sa.Integer(), nullable=False),
    sa.CheckConstraint('processing_time >= 0', name=op.f('ck_operation_machine_alternatives_processing_time_nonnegative')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_operation_machine_alternatives_instance_id_instances')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_operation_machine_alternatives_machine_id_machines')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_machine_alternatives_operation_id_operations')),
    sa.PrimaryKeyConstraint('instance_id', 'operation_id', 'machine_id', name=op.f('pk_operation_machine_alternatives'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('operation_machine_alternatives')
    op.drop_index(op.f('ix_setup_times_instance_id'), table_name='setup_times')
    op.drop_table('setup_times')
    op.drop_index(op.f('ix_operations_instance_id'), table_name='operations')
    op.drop_table('operations')
    op.drop_index(op.f('ix_machine_capabilities_instance_id'), table_name='machine_capabilities')
    op.drop_table('machine_capabilities')
    op.drop_index(op.f('ix_machines_instance_id'), table_name='machines')
    op.drop_table('machines')
    op.drop_index(op.f('ix_jobs_instance_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_job_families_instance_id'), table_name='job_families')
    op.drop_table('job_families')
    # ### end Alembic commands ###
