"""provenance tables

Revision ID: 4b782d560dd7
Revises: 
Create Date: 2026-08-23 02:48:57.576178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4b782d560dd7'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('source_name', sa.String(length=120), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('source_version', sa.String(length=80), nullable=True),
    sa.Column('source_license', sa.String(length=200), nullable=True),
    sa.Column('retrieved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('source_checksum', sa.String(length=64), nullable=True),
    sa.Column('source_time_unit', sa.String(length=40), nullable=False),
    sa.Column('time_scale_to_minutes', sa.Float(), nullable=False),
    sa.Column('normalized_time_unit', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instances')),
    sa.UniqueConstraint('name', name=op.f('uq_instances_name'))
    )
    op.create_table('instance_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('profile_type', sa.String(length=60), nullable=False),
    sa.Column('parameters_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('source_instance_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['source_instance_id'], ['instances.id'], name=op.f('fk_instance_profiles_source_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instance_profiles'))
    )
    op.create_table('scenario_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scenario_id', sa.Integer(), nullable=False),
    sa.Column('source_instance_id', sa.Integer(), nullable=False),
    sa.Column('contribution_type', sa.String(length=60), nullable=False),
    sa.Column('transformation_description', sa.Text(), nullable=False),
    sa.Column('random_seed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['scenario_id'], ['instances.id'], name=op.f('fk_scenario_sources_scenario_id_instances')),
    sa.ForeignKeyConstraint(['source_instance_id'], ['instances.id'], name=op.f('fk_scenario_sources_source_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scenario_sources'))
    )
    op.create_index(op.f('ix_scenario_sources_scenario_id'), 'scenario_sources', ['scenario_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scenario_sources_scenario_id'), table_name='scenario_sources')
    op.drop_table('scenario_sources')
    op.drop_table('instance_profiles')
    op.drop_table('instances')
    # ### end Alembic commands ###
