"""workers materials tables

Revision ID: 54f04938b3e1
Revises: 38432f3997b1
Create Date: 2026-08-23 03:08:13.730767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54f04938b3e1'
down_revision: Union[str, Sequence[str], None] = '38432f3997b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('sku', sa.String(length=80), nullable=False),
    sa.Column('initial_stock', sa.Integer(), nullable=False),
    sa.Column('reorder_point', sa.Integer(), nullable=True),
    sa.CheckConstraint('initial_stock >= 0', name=op.f('ck_materials_stock_nonnegative')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_materials_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_materials'))
    )
    op.create_index(op.f('ix_materials_instance_id'), 'materials', ['instance_id'], unique=False)
    op.create_table('worker_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_worker_roles_instance_id_instances')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_roles')),
    sa.UniqueConstraint('id', 'instance_id', name='uq_worker_roles_id_instance')
    )
    op.create_index(op.f('ix_worker_roles_instance_id'), 'worker_roles', ['instance_id'], unique=False)
    op.create_table('material_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('available_at', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.CheckConstraint('quantity > 0 AND available_at >= 0', name=op.f('ck_material_receipts_receipt_valid')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_material_receipts_instance_id_instances')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_material_receipts_material_id_materials')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_material_receipts'))
    )
    op.create_index(op.f('ix_material_receipts_instance_id'), 'material_receipts', ['instance_id'], unique=False)
    op.create_table('workers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.String(length=60), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.CheckConstraint("status IN ('AVAILABLE','UNAVAILABLE')", name=op.f('ck_workers_worker_status')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_workers_instance_id_instances')),
    sa.ForeignKeyConstraint(['role_id'], ['worker_roles.id'], name=op.f('fk_workers_role_id_worker_roles')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workers')),
    sa.UniqueConstraint('id', 'instance_id', name='uq_workers_id_instance')
    )
    op.create_index(op.f('ix_workers_instance_id'), 'workers', ['instance_id'], unique=False)
    op.create_table('worker_availability_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('available_from', sa.Integer(), nullable=False),
    sa.Column('available_until', sa.Integer(), nullable=False),
    sa.Column('source_pattern', sa.String(length=80), nullable=False),
    sa.CheckConstraint('available_until >= available_from', name=op.f('ck_worker_availability_windows_window_order')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_worker_availability_windows_instance_id_instances')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_availability_windows_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_availability_windows'))
    )
    op.create_index(op.f('ix_worker_availability_windows_instance_id'), 'worker_availability_windows', ['instance_id'], unique=False)
    op.create_table('operation_bom',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('quantity_required', sa.Integer(), nullable=False),
    sa.CheckConstraint('quantity_required > 0', name=op.f('ck_operation_bom_qty_positive')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_operation_bom_instance_id_instances')),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], name=op.f('fk_operation_bom_material_id_materials')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_bom_operation_id_operations')),
    sa.PrimaryKeyConstraint('instance_id', 'operation_id', 'material_id', name=op.f('pk_operation_bom'))
    )
    op.create_table('operation_machine_worker_times',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('operation_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('processing_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_operation_machine_worker_times_instance_id_instances')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_operation_machine_worker_times_machine_id_machines')),
    sa.ForeignKeyConstraint(['operation_id'], ['operations.id'], name=op.f('fk_operation_machine_worker_times_operation_id_operations')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_operation_machine_worker_times_worker_id_workers')),
    sa.PrimaryKeyConstraint('instance_id', 'operation_id', 'machine_id', 'worker_id', name=op.f('pk_operation_machine_worker_times'))
    )
    op.create_foreign_key(op.f('fk_jobs_job_family_id_job_families'), 'jobs', 'job_families', ['job_family_id'], ['id'])
    op.create_foreign_key(op.f('fk_operations_required_role_id_worker_roles'), 'operations', 'worker_roles', ['required_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_operations_required_role_id_worker_roles'), 'operations', type_='foreignkey')
    op.drop_constraint(op.f('fk_jobs_job_family_id_job_families'), 'jobs', type_='foreignkey')
    op.drop_table('operation_machine_worker_times')
    op.drop_table('operation_bom')
    op.drop_index(op.f('ix_worker_availability_windows_instance_id'), table_name='worker_availability_windows')
    op.drop_table('worker_availability_windows')
    op.drop_index(op.f('ix_workers_instance_id'), table_name='workers')
    op.drop_table('workers')
    op.drop_index(op.f('ix_material_receipts_instance_id'), table_name='material_receipts')
    op.drop_table('material_receipts')
    op.drop_index(op.f('ix_worker_roles_instance_id'), table_name='worker_roles')
    op.drop_table('worker_roles')
    op.drop_index(op.f('ix_materials_instance_id'), table_name='materials')
    op.drop_table('materials')
    # ### end Alembic commands ###
