"""downtime and telemetry

Revision ID: c1f9d2f0bcdf
Revises: 54f04938b3e1
Create Date: 2026-08-23 03:13:40.077564

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c1f9d2f0bcdf'
down_revision: Union[str, Sequence[str], None] = '54f04938b3e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.execute("CREATE EXTENSION IF NOT EXISTS timescaledb;")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machine_downtime_windows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('downtime_from', sa.Integer(), nullable=False),
    sa.Column('downtime_until', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('source_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('downtime_until IS NULL OR downtime_until > downtime_from', name=op.f('ck_machine_downtime_windows_downtime_interval_valid')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_machine_downtime_windows_instance_id_instances')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_machine_downtime_windows_machine_id_machines')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_machine_downtime_windows'))
    )
    op.create_index(op.f('ix_machine_downtime_windows_instance_id'), 'machine_downtime_windows', ['instance_id'], unique=False)
    op.create_table('telemetry_events',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('occurred_at', sa.Integer(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.String(length=160), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=40), nullable=False),
    sa.Column('received_at', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('estimated_downtime', sa.Integer(), nullable=True),
    sa.Column('processed_at', sa.Integer(), nullable=True),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('payload_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('occurred_at >= 0', name=op.f('ck_telemetry_events_occurred_nonnegative')),
    sa.CheckConstraint('received_at >= 0', name=op.f('ck_telemetry_events_received_nonnegative')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_telemetry_events_instance_id_instances')),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], name=op.f('fk_telemetry_events_machine_id_machines')),
    sa.PrimaryKeyConstraint('id', 'occurred_at', name=op.f('pk_telemetry_events'))
    )
    op.create_index(op.f('ix_telemetry_events_instance_id'), 'telemetry_events', ['instance_id'], unique=False)
    op.create_index(op.f('ix_telemetry_events_occurred_at'), 'telemetry_events', ['occurred_at'], unique=False)
    op.create_index('ix_telemetry_message_id', 'telemetry_events', ['message_id'], unique=False)
    # ### end Alembic commands ###
    op.execute(
        "SELECT create_hypertable("
        "'telemetry_events', 'occurred_at', "
        "chunk_time_interval => 10080);"
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.execute("SELECT drop_chunks('telemetry_events', older_than => 0::bigint);")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_telemetry_message_id', table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_occurred_at'), table_name='telemetry_events')
    op.drop_index(op.f('ix_telemetry_events_instance_id'), table_name='telemetry_events')
    op.drop_table('telemetry_events')
    op.drop_index(op.f('ix_machine_downtime_windows_instance_id'), table_name='machine_downtime_windows')
    op.drop_table('machine_downtime_windows')
    # ### end Alembic commands ###
