"""multi resource telemetry

Revision ID: e1ebd45ab922
Revises: c1f9d2f0bcdf
Create Date: 2026-08-23 19:28:07.068611

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e1ebd45ab922'
down_revision: Union[str, Sequence[str], None] = 'c1f9d2f0bcdf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_absence_windows',
    sa.Column('id', sa.Integer(), sa.Identity(always=False), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('worker_id', sa.Integer(), nullable=False),
    sa.Column('absence_from', sa.Integer(), nullable=False),
    sa.Column('absence_until', sa.Integer(), nullable=True),
    sa.Column('reason', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=True),
    sa.Column('source_event_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.CheckConstraint('absence_until IS NULL OR absence_until > absence_from', name=op.f('ck_worker_absence_windows_absence_interval_valid')),
    sa.ForeignKeyConstraint(['instance_id'], ['instances.id'], name=op.f('fk_worker_absence_windows_instance_id_instances')),
    sa.ForeignKeyConstraint(['worker_id'], ['workers.id'], name=op.f('fk_worker_absence_windows_worker_id_workers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_worker_absence_windows'))
    )
    op.create_index(op.f('ix_worker_absence_windows_instance_id'), 'worker_absence_windows', ['instance_id'], unique=False)
    op.add_column('telemetry_events', sa.Column('worker_id', sa.Integer(), nullable=True))
    op.add_column('telemetry_events', sa.Column('material_id', sa.Integer(), nullable=True))
    # Staged default backfills existing rows as MACHINE, then the default is
    # removed so new inserts must set resource_kind explicitly.
    op.add_column('telemetry_events', sa.Column('resource_kind', sa.String(length=20), nullable=False, server_default='MACHINE'))
    op.alter_column('telemetry_events', 'resource_kind', existing_type=sa.String(length=20), existing_nullable=False, server_default=None)
    op.alter_column('telemetry_events', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_foreign_key(op.f('fk_telemetry_events_worker_id_workers'), 'telemetry_events', 'workers', ['worker_id'], ['id'])
    op.create_foreign_key(op.f('fk_telemetry_events_material_id_materials'), 'telemetry_events', 'materials', ['material_id'], ['id'])
    op.create_check_constraint(op.f('ck_telemetry_events_exactly_one_resource'), 'telemetry_events', '((machine_id IS NOT NULL)::int + (worker_id IS NOT NULL)::int + (material_id IS NOT NULL)::int) = 1')
    op.create_check_constraint(op.f('ck_telemetry_events_resource_kind_domain'), 'telemetry_events', "resource_kind IN ('MACHINE','WORKER','MATERIAL')")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('ck_telemetry_events_resource_kind_domain'), 'telemetry_events', type_='check')
    op.drop_constraint(op.f('ck_telemetry_events_exactly_one_resource'), 'telemetry_events', type_='check')
    op.drop_constraint(op.f('fk_telemetry_events_material_id_materials'), 'telemetry_events', type_='foreignkey')
    op.drop_constraint(op.f('fk_telemetry_events_worker_id_workers'), 'telemetry_events', type_='foreignkey')
    op.alter_column('telemetry_events', 'machine_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('telemetry_events', 'resource_kind')
    op.drop_column('telemetry_events', 'material_id')
    op.drop_column('telemetry_events', 'worker_id')
    op.drop_index(op.f('ix_worker_absence_windows_instance_id'), table_name='worker_absence_windows')
    op.drop_table('worker_absence_windows')
    # ### end Alembic commands ###
